apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app: vault
resources:
- vault-statefulset.yaml
- vault-service-active.yaml
- vault-serviceaccount.yaml
- vault-role.yaml
- vault-rolebinding.yaml
configMapGenerator:
- name: vault-config
  files:
  - conf/vault.hcl