apiVersion: v1
kind: Service
metadata:
  name: vault-active
spec:
  publishNotReadyAddresses: false
  ports:
  - name: ui
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: raft
    port: 8201
    targetPort: 8201
    protocol: TCP
  selector:
    vault-active: "true"