apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  replicas: 3
  serviceName: vault-headless
  template:
    spec:
      serviceAccountName: vault
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data 
        emptyDir: {}
      containers:
      - name: vault
        image: vault:1.9.4
        command: ["/bin/vault", "server", "-config=/etc/vault.d/vault.hcl"]
        ports:
        - name: ui
          containerPort: 8200
        readinessProbe:
          exec:
            command: ["vault", "status", "-tls-skip-verify"]
        env:
        - name: VAULT_LOG_LEVEL
          value: debug
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ADDR
          value: 'http://127.0.0.1:8200'
        - name: VAULT_CONFIG_DIR
          value: /etc/vault.d
        - name: VAULT_RAFT_PATH
          value: /vault/data
        - name: VAULT_API_ADDR
          value: 'http://$(POD_IP):8200'
        - name: VAULT_CLUSTER_ADDR
          value: "https://$(HOSTNAME).vault-headless:8201"
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault.d/
        - name: vault-data
          mountPath: /vault/data