apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  template:
    spec:
      serviceAccountName: vault
      volumes:
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: sys
        hostPath:
          path: /sys
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data 
        emptyDir: {}
      containers:
      - name: vault
        image: vault:1.9.4
        command: ["/bin/vault", "server", "-config=/etc/vault.d/vault.hcl"]
        securityContext:
          privileged: true
        ports:
        - name: ui
          containerPort: 8200
        readinessProbe:
          exec:
            command: ["vault", "status", "-tls-skip-verify"]
        env:
        - name: VAULT_LOG_LEVEL
          value: debug
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VAULT_RAFT_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ADDR
          value: 'http://127.0.0.1:8200'
        - name: VAULT_CONFIG_DIR
          value: /etc/vault.d
        - name: VAULT_API_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_RAFT_PATH
          value: /vault/data
        - name: VAULT_CLUSTER_ADDR
          value: "http://$(HOSTNAME):8201"
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault.d/
        - name: vault-data
          mountPath: /vault/data
        - name: lib-modules 
          mountPath: /lib/modules
        - name: sys
          mountPath: /sys
        - name: usr-src
          mountPath: /usr/src